### ISSUE TITLE
Implement "help" subcommands

### ISSUE THREAD

**Issue by jyun-zalando** [zalando-incubator/pazuzu#104]
Implement help subcommand proper CLI-way. Currently it uses `fmt.print` statements.

SEE: https://github.com/zalando-incubator/pazuzu/pull/103#discussion_r89288153

**Comment by fehmicansaglam** [comment]
This is already done in https://github.com/zalando-incubator/pazuzu/commit/0c6946b25e755c253f22e3bbaa002a18a3df3449
