### ISSUE TITLE
Changing default git project

### ISSUE THREAD

**Issue by rdllopes** [zalando-incubator/pazuzu#107]
Right now, pazuzu is using by default Sangdol:pazuzu-test-repo as git repository. However, to be able to expand, modify, etc test scenarios, we need to move git repository to other place. That would be zalando-incubator pazuzu.

**Comment by netme** [comment]
I think we can already move this to Done

**Comment by netme** [comment]
According to @pgronkiewicz we are starting a new repo today. Currently fixtures are located in zalando-incubator/pazuzu and Sangdol/pazuzu-test-repo is not used.

**Comment by erthalion** [comment]
So, I believe this issue definitely can be closed right now to reduce total amount of entropy, am I correct?

**Comment by netme** [comment]
@erthalion yes, you are right.
