### ISSUE TITLE
Create Pazuzufile Safe Way

### ISSUE THREAD

**Issue by netme** [zalando-incubator/pazuzu#108]
Currently we are re-creating `Pazuzufile` every time we are running `pazuzu compose`. If multiple processes will run, it can lead to the conflicts during write. Find a proper solution to this problem.

**Comment by netme** [comment]
The cases of race-condition will happen rare. Still under discussion.

**Comment by otrosien** [comment]
Don't think this will ever be a real problem...

**Comment by netme** [comment]
We can close it
