### ISSUE TITLE
Choose base image when composing Pazuzufile

### ISSUE THREAD

**Issue by zayim** [zalando-incubator/pazuzu#187]
Currently, when composing a new Pazuzufile, default base image from global config is always used. Add option to override this when composing file.
Add param (`--base` or `-b` or similar) to `pazuzu compose` command line. String entered should be used in Docker- and Pazuzu- file.

**Comment by Deep-1991** [comment]
As Schlomo said, what if I have centos and name it as ubuntu with proper naming convention, just to mess up. Will that be checked?

**Comment by otrosien** [comment]
@Deep-1991 what's important is the result. If the bats test succeeds when applying your snippet, then it doesn't matter if you applied a centos feature to an ubuntu base image or vice versa. 

On the other hand, the review process should include checking if you created a feature inside ubuntu space that uses yum install or similar.

**Comment by otrosien** [comment]
I really like it. From a feature perspective you only need to make sure the snippet is compatible to a specific distro + version. You don't need to think about docker base images, but you may specify further restrictions or compatibilities/incompatibilities in the feature description.

From a user perspective we're making selecting the base image more explicit. Inside your Pazuzufile the feature naming convention makes it obvious on first sight if you have selected the proper features. You probably should add comments on why you chose a feature from a different distro or base version.

**Comment by otrosien** [comment]
Extracted the feature naming convention into this issue: https://github.com/zalando-incubator/pazuzu/issues/188

**Comment by otrosien** [comment]
Done.
