### ISSUE TITLE
Support HTTPS protocol for registry

### ISSUE THREAD

**Issue by zayim** [zalando-incubator/pazuzu#190]
Currently, CLI can only connect to registry via HTTP. Implement ability to connect to registry via HTTPS, too.

Suggestion: add additional parameter (`scheme` or `protocol`, etc) in configuration, and based on its value, create HTTP client or HTTPS client.

**Comment by otrosien** [comment]
Closed via 201a142c6d8956d2597f5b1c8d35ba0e5f6d6709
