### ISSUE TITLE
Update project configuration cli interface

### ISSUE THREAD

**Issue by slothspot** [zalando-incubator/pazuzu#216]

**Comment by slothspot** [comment]
![cli_actions](https://cloud.githubusercontent.com/assets/760295/24007404/bab616f8-0a6e-11e7-9589-2625bb563217.png)

**Comment by fehmicansaglam** [comment]
What does `update features` mean? Upgrade to the latest version of the feature?

**Comment by slothspot** [comment]
Yes, as we discussed:
adding feature is a fixation of it version in config, so update is needed to update versions fixed in config

**Comment by fehmicansaglam** [comment]
Just thinking... If everything is considered a configuration then we may generalize commands to `set, add, remove, get`. Commands should behave appropriately according to the value type (array or a single value). If we do this then `feature update` becomes a different command like build and test. 

```
pazuzu config set base <base>
pazuzu config add feature java
pazuzu config remove feature node:6.0.0
pazuzu config get base
pazuzu config get feature
```

**Comment by slothspot** [comment]
I have an idea that cli interface will be like this:
![screen shot 2017-03-17 at 10 38 57](https://cloud.githubusercontent.com/assets/760295/24037417/056e06f8-0afe-11e7-9753-93a3468013a8.png)

**Comment by slothspot** [comment]
BTW, there is -v (verbose) flag but it affects log.Printf only which is not used in project (plain fmt.printf is used instead); so should I remove this option or it would be better make log usage mandatory?

**Comment by slothspot** [comment]
#220 created to track logging update process

**Comment by slothspot** [comment]
Merged
