### ISSUE TITLE
Remove pazuzu.txt?

### ISSUE THREAD

**Issue by slothspot** [zalando-incubator/pazuzu#223]
We have pazuzu.txt file which is the man page for pazuzu. So I have questions about it:
1. Should we update it and maintain?
or
2. Should we remove it?

I propose to remove it from repo.

**Comment by erthalion** [comment]
Maybe we can generate this man page automatically from the readme file?

**Comment by slothspot** [comment]
Found several posible options:
1. https://rtomayko.github.io/ronn/ronn.1.html
2. https://github.com/sunaku/md2man
Worth to check how these tools may help
