### ISSUE TITLE
Single-source swagger.yaml file

### ISSUE THREAD

**Issue by mtrenkmann** [zalando-incubator/pazuzu#229]
Currently, there is a version of `swagger.yaml` in this repo and in [pazuzu-registry](https://github.com/zalando-incubator/pazuzu-registry/blob/master/src/main/resources/api/swagger.yaml) which define the same REST API. The former one is needed to generate client code for the CLI, the latter one is needed to generate code for the actual server. For maintainability reasons, there should be only one of it and I think the right place would be the one in the pazuzu-registry project, because here is where the API is provided. At the moment both files are already out of sync.

**Solutions** we discussed so far:

1. Merging the repos `pazuzu` and `pazuzu-registry`. Keep only one `swagger.yaml`.
2. Making `pazuzu-registry` a submodule of `pazuzu`. Keep only the `swagger.yaml` in `pazuzu-registry`.
3. Keep only the `swagger.yaml` in `pazuzu-registry` and require devs of `pazuzu` to clone `pazuzu-registry` as well in order the generate the client code.

I would recommend option 3.

**Comment by slothspot** [comment]
I would add option 4:
fetch `swagger.yaml` from `pazuzu-registry` using `install-dependencies.sh` script, since I don't think that full `pazuzu-registry` repo clone is needed working on pazuzu cli only.

**Comment by mtrenkmann** [comment]
Ok, but this also means that `install-dependencies.sh` fetches `swagger.yaml` always from `pazuzu-registry/master`. If I am on a develop or feature branch, I probably want to fetch a `swagger.yaml` from `pazuzu-registry/develop` as well. In that case I must edit the `install-dependencies.sh` in my develop branch two times: first time to let it point to `pazuzu-registry/develop/swagger.yaml` and the second time when I merge this branch into the master.

If I clone the entire `pazuzu-registry` next to `pazuzu`, I don't have to touch `install-dependencies.sh`. I just have to make sure that I checkout the proper branch in `pazuzu-registry`. Both approaches have pros and cons.

Any other comments on this, maybe from @pgronkiewicz or @netme

**Comment by slothspot** [comment]
We may use some env variable like `SWAGGER_LOCAL` to define where to search API definition.
By default `SWAGGER_LOCAL=0`: fetch definition from `pazuzu-registry` upstream master;
if `SWAGGER_LOCAL=1`: use definition from `../pazuzu-registry/src/main/resources/api/swagger.yaml`

**Comment by mtrenkmann** [comment]
So since @pgronkiewicz supports option 3 (and sees option 4 as a suboption of 3) I will manage to get the most recent version of `swagger.yaml` into `pazuzu-registry` and I will also delete it in the `pazuzu` project.

@slothspot do you have time to provide PRs for fetching `swagger.yaml` from `pazuzu` the way you proposed it?

**Comment by slothspot** [comment]
@mtrenkmann Ye, no problem. I'll prepare such PR for `pazuzu`

**Comment by slothspot** [comment]
Merged
