### ISSUE TITLE
Definition of the command line interface

### ISSUE THREAD

**Issue by stoewer** [zalando-incubator/pazuzu#47]
Add a file `CLI.md` to the repository which describes pazuzus' command line interface and how it can be used to perform a certain task.

Feel free to edit this issue in order to make it more extensive and precise.

**Comment by krapivchenkon** [comment]
# Pazuzu CLI
## Workflow
Basicaly flow of using pazuzu cli tool has 3 steps:
- **search** - search for available features
- **compose** - compose Pazuzufile with desired features
- **build** - create Dockerfile out of Pazuzufile

## Search features
List step is used to check what features are actually available in configured snippet provider
```
$ pazuzu search [mask]
```
Mask is a valid regexp, i.e.:
```
$ pazuzu search node-v4.6*|java8|mvn
```
Mask `node-v4.6*|java8|mvn` will use following features:
- latest `node` version that match regexp **node-v4.6***
- latest `java8` release available in feature snippets provider(default java8 )

## Compose features
Compose step actually creates features file out of specified 
```
$ pazuzu compose <space-separated-feature-names> 
```
### Available options
- **--with-base NAME** - specify base image
- **-o/--out FILENAME** - specify name of the output features file. Default is Pazuzu file
### Examples:
`$ pazuzu compose node java8` - generate Pazuzufile from the list of features

`$ pazuzu compose node java8 --out node-und-java8.yml` - Save everything to **node-und-java8.yml** file

## Build Dockerfile
This step aims to actually create **Dockerfile** out of the snippets configured for features.

`$ pazuzu build . `  - Builds a **Dockerfile** from **Pazuzufile** located in the current directory.

` $ pazuzu build <node-with-babel.yml>` - Builds a **Dockerfile** from specified feature file.

**NOTE:** build command gives a sample command of how to run `docker
build` 

## Run docker build
Execute `docker build` command to actually create image


# Installation and Configuration
All set configuration will be stored ` ~/.pazuzu_conf`

-  Setup snippets provider:

    ```
    $ pazuzu config set git.url git@github.com:zalando-incubator/pazuzu.git
    $ pazuzu cinfig set github.url https://github.com/zalando-incubator/pazuzu.git
    ```
- Setup base image

	```
	$ pazuzu config set base-image ubuntu:16.04
	```

**Comment by Sangdol** [comment]
Regarding `search` command, in Homebrew or npm they allow regexp search only when the search term is enclosed by `/`. And when the search term is a normal text, they show all the results which contains the search term. I guess it'd be better for us to take this approach as well. 

For example,
```
$ brew search tig
antigen               certigo               tig ✔                 wiredtiger
homebrew/x11/tiger-vnc                       Caskroom/cask/tigervnc-viewer

$ brew search /t.g/                                  .zprezto/git/master !+
antigen               git-gerrit            puddletag             tig ✔
autogen               git-integration       pygtkglext            txt2tags
certigo               gotags                rbenv-ctags           vramsteg
ctags                 gtk-mac-integration   rbenv-default-gems    wiredtiger
exiftags              gtkglext              rtags                 xmlcatmgr
fastcgi               libid3tag             tag
flactag               montage               taglib
homebrew/apache/mod_fastcgi                  homebrew/games/git-game
homebrew/emacs/ggtags                        homebrew/x11/tiger-vnc
```

Also FYI, if you use `*` in the command line without quoting or escaping, it could expand.

**Comment by krapivchenkon** [comment]
To keep things easier we will keep only regexps for the moment as input parameter, so it might look like:
```
$ pazuzu search "java*"
java --> java8
java7
java8
```

**Comment by Sangdol** [comment]
It's okay to use quotes instead of `/`. If `search` takes regexps, I guess the example should be like this - `.` is missing in the example.

```
$ pazuzu search "java.*"
java --> java8
java7
java8
```

**Comment by krapivchenkon** [comment]
yes, you're right, wildmask should contain **.***
