### ISSUE TITLE
Define pazuzus' architecture

### ISSUE THREAD

**Issue by stoewer** [zalando-incubator/pazuzu#49]
Add a file to the repository that describes and depicts pazuzus' architecture.

Feel free to edit this issue in order to make it more extensive and precise.

**Comment by elgris** [comment]
![pazuzu_diagram](https://cloud.githubusercontent.com/assets/1905821/19641607/b05fc652-99e1-11e6-8ba5-b54ea59f8217.png)
a draft of diagram explaining how things communicate to each other. Colored components are shared. It would be great to know all teammember's opinion about interfaces defined

**Comment by nayef** [comment]
Directory structure for git back end repo

```
Repo
    |
    features
            |
            featureName
                      |
                       ------- meta.yml (contains feature dependencies, description etc)
                       ------- Dockerfile (contains docker snippet for this feature)
                       ------- test.sh (contains test script for this feature)

```

**Comment by Sangdol** [comment]
Please check the sample repo for testing Pazuzu - https://github.com/Sangdol/pazuzu-test-repo.

The Dockerfiles are from [the sample file](https://github.bus.zalan.do/continuous-delivery/jenkins-fat-master/blob/master/Dockerfile).

I've added some sample features for testing dependencies, which are `A`, `B`, and `C`.

Feel free to tweak the repo.

**Comment by netme** [comment]
Already defined. Closing.
