### ISSUE TITLE
Implement an interface for building connectors for datastorage

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#50]
## User story

As a developer I would like to have an interface defined and described that helps me to implement communication between Pazuzu and data source.

Data source is a place where Features are stored. For now we're going to use Git as a data source.
## Additional information

The interface is described in following diagram: https://github.com/zalando-incubator/pazuzu/issues/49#issuecomment-255699263
## Acceptance criteria
- [x] interface `IStorageConnector`, data types `Feature` and `FeatureMeta` are implemented.
- [ ] stub implementation of `IStorageConnector is provided

**Comment by stoewer** [comment]
Was resolved by #55

**Comment by netme** [comment]
Already implemented.
