### ISSUE TITLE
[infrastructure] Prepare an environment to build pazuzu automatically

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#51]
## User story

As a developer I want to have a tool that runs tests and builds pazuzu binary on demand with some build service (Jenkins?).
## Acceptance criteria
- [ ] Jenkins settings for `pazuzu` are defined.
- [ ] Jenkins runs static analysis tools (`go vet`, `golint`) and publishes useful stats
- [ ] Jenkins runs tests

**Comment by netme** [comment]
Done by @rafaelsbz
