### ISSUE TITLE
Implement pazuzu command line interface

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#52]
## User story

As a user of `pazuzu` I want to have a CLI with documentation
## Acceptance criteria
- [ ] CLI is defined according to https://github.com/zalando-incubator/pazuzu/issues/47
- [ ] CLI is implemented and wired againts mock of `IStorageInterface` (https://github.com/zalando-incubator/pazuzu/issues/50)
- [ ] Tests are provided

**Comment by netme** [comment]
Mostly done during November. All missing features are mentioned as separate issues.
