### ISSUE TITLE
Create a repository with sample Features

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#53]
## User story

As a developer I need a test repository with a small set of Features that form actual Dockerfile. This set of Features will be used to verify that `pazuzu` fetches Features correct and builds Dockerfile correct.

## Acceptance criteria
- [x] git repository for Pazuzu test Features is created
- [x] 5-7 example Features are created in that repository. Example Features form actual Dockerfile (you can pick one or two big dockerfiles from https://hub.docker.com/ and split it into Features)
- [ ] There is at least 2 levels of nesting present (a Feature has dependency with dependency)

**Comment by Sangdol** [comment]
Please check the sample repo for testing Pazuzu - https://github.com/Sangdol/pazuzu-test-repo.

The Dockerfiles are from [the sample file](https://github.bus.zalan.do/continuous-delivery/jenkins-fat-master/blob/master/Dockerfile).

I've added some sample features for testing dependencies, which are `A`, `B`, and `C`.

For now, every files in the feature directory can be optional.

Feel free to tweak the repo.

**Comment by elgris** [comment]
The issue is finished and can be closed
