### ISSUE TITLE
Leave documentation for the next team

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#66]
## User story

As a developer from the future :) I want to have some documentation and ideas left by previous team. It will help me start working on a project faster.
## Acceptance criteria
- [x] TODO list is specified in `README.md`. Including extension of existing data structures.
- [x] CLI tool commands are described in Wiki
- [x] Flow diagrams for each CLI command are posted to Wiki
- [x] Architecture diagrams for whole Pazuzu tool is posted to Wiki
- [ ] Directory structure used by Git storage is described in Wiki (explanation of which part of data structure is responsible for what is included: file names, directory names)

**Comment by netme** [comment]
Done
