### ISSUE TITLE
Move test repository with Features inside our codebase

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#67]
## User story

As a developer I want to be able to run tests for `Git` storage connector locally with no external dependencies

## Acceptance criteria

- [x] Test features moved to https://github.com/Sangdol/pazuzu-test-repo to `storageconnector/fixtures/git`
- [x] Tests for `Git` storage connector are wired to local fixtures

**Comment by stoewer** [comment]
Resolved via #74
