### ISSUE TITLE
Implement Pazuzufile reader and writer

### ISSUE THREAD

**Issue by elgris** [zalando-incubator/pazuzu#68]
## User story

As a user of Pazuzu I need to be able to create Pazuzufile and feed it back to `pazuzu`
## Acceptance criteria
- [ ] Structure of Pazuzufile is defined in `pazuzufile.go`
- [ ] Function for reading Pazuzufile is implemented. Definition of the function: `func Read(io.Reader) (Pazuzufile, error)`
- [ ] Function for writing Pazuzufile is implemented. Definition of the function: `func Write(io.Writer, Pazuzufile) error`
- [ ] Tests for reading and writing Pazuzufile are provided as well

**Comment by nayef** [comment]
in the presentation the file looks like
<pre>
base: ubuntu:willy
features:
    -Java8
    -AnotherFeature
push:urlToJenkins
</pre>

As we will not be allowing selection of base image or pushing of image, All we have is the features.
So I propose pazuzu file to be a simple text file with one feature per line. Like the following

<pre>
Java8
AnotherFeature
OneMoreFeature
</pre>

Please let me know your thoughts.

**Comment by stoewer** [comment]
I think the yaml structure is more extensible, but we don't really need base and push at the moment.

**Comment by nayef** [comment]
So we can go with a yml like following
<pre>
Base: baseName
Features:
    -Java8
    -AnotherFeature
</pre>

**Comment by netme** [comment]
Done
